version: '2.1'
services:
  web:
    image: "ket4yii/php-censor:web"
    ports:
    - "80:80"
    networks:
    - default 
    depends_on:
      mysql:
        condition: service_started
      queue:
        condition: service_started
    env_file:
    - ./env/phpcensor.env
  worker:
    image: "ket4yii/php-censor:worker"
    networks:
    - default 
    depends_on:
      mysql:
        condition: service_started
      queue:
        condition: service_started
    env_file:
    - ./env/phpcensor.env
  mysql:
    image: "mysql"
    networks:
      default:
        aliases:
        - db
    env_file:
    - ./env/mysql.env
  queue:
    image: "schickling/beanstalkd"
    networks:
      default:
        aliases:
        - beanstalk
